name: news_app
description: News App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_bloc: ^7.3.3
  equatable: ^2.0.3
  dio: ^4.0.6
  intl:
  timeago:
  cached_network_image: ^3.2.0
  share_plus: ^4.0.4
  webview_flutter:
  form_field_validator:
  flutter_launcher_icons:
  lottie:


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/istockphoto-933421794-612x612.jpeg"

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/logo/
